title: Michael's Website
description: A website for Michael Ruoxi Li
author: Michael Ruoxi Li
theme: just-the-docs

url: https://michaelliruoxi.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  Google: https://google.com
